"""init schema

Revision ID: b96b354190a3
Revises: 
Create Date: 2025-10-29 21:14:44.064997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96b354190a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_sec', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retained_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('queued','processing','done','failed')", name='ck_upload_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'sha256', name='uq_upload_meeting_sha256')
    )
    op.create_table('summary_bullet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('summary_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('upload_object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'object_key', name='uq_bucket_object_key')
    )
    op.create_table('transcript_segment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('t_start', sa.Numeric(), nullable=False),
    sa.Column('t_end', sa.Numeric(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bullet_citation',
    sa.Column('summary_bullet_id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['summary_bullet_id'], ['summary_bullet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_bullet_id', 'segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bullet_citation')
    op.drop_table('transcript_segment')
    op.drop_table('upload_object')
    op.drop_table('transcript')
    op.drop_table('summary_bullet')
    op.drop_table('upload')
    op.drop_table('summary')
    # ### end Alembic commands ###
